<html>
   <head>
      <title>
         Dabbulu Urike Raavu
      </title>
      <link rel = "icon" 
            href ="Logo_of_Dream11.png" 
            type = "image/x-icon">
        <link rel="stylesheet"
         type="text/css"
         href="web.css"
         />
      <style>
         table {
            border: 1 px white;
         }
      </style>

   </head>
   <STYLE>A {text-decoration: none;} </STYLE>
   <body>
       <a href="Dabbulu Urike Raavu.html">
         Home
      </a>
      &nbsp
       <a href="Money.html">
         Money
      </a>
      <h1>Muskoni kindana chudu..</h1><h1>Dabbulu evariki entha ochayo telustadhi</h1>
      <table>
         <tr>
            <th>Match number</th><th></th>
            <th>Anudeep</th><th></th>
            <th>Mahaveer</th><th></th>
            <th>Karthik</th><th></th>
            <th>venu</th><th></th>
            <th>Madhav</th><th></th>
            <th>Prabhat</th><th></th>
            <th>Koundinya</th><th></th>
            <th>Laxmi narayana</th>
         </tr>
         <tr>
            <td>Until 5th match</td><td></td><td>27</td><td></td><td>11.8333</td><td></td><td>-14</td><td></td><td>-8.6667</td><td></td><td>6.8333</td><td></td><td>-26.1666</td><td></td><td>3.16667</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>6</td><td></td><td>0</td><td></td><td>-7</td><td></td><td>15</td><td></td><td>-20</td><td></td><td>-5</td><td></td><td>-10</td><td></td><td>27</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>7</td><td></td><td>-5</td><td></td><td>-10</td><td></td><td>40</td><td></td><td>-15</td><td></td><td>-3</td><td></td><td>10</td><td></td><td>-17</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>8</td><td></td><td>-20</td><td></td><td>5</td><td></td><td>8</td><td></td><td>10</td><td></td><td>-3</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>9</td><td></td><td>5</td><td></td><td>0</td><td></td><td>0</td><td></td><td>3</td><td></td><td>6</td><td></td><td>-10</td><td></td><td>-4</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>10</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>11</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>12</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>13</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>14</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>15</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>16</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>17</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>18</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>19</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>20</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>21</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>22</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>23</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>24</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>25</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>26</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>27</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>28</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>29</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>30</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>31</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>32</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>33</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>34</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>35</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>36</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>37</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>38</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>39</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>40</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>41</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>42</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>43</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>44</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>45</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>46</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>47</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>48</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>49</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>50</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>51</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>52</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>53</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>54</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>55</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>56</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>Qualifier 1</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>Eliminator</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>Qualifier 2</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>Final</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td><td></td><td>0</td>
         </tr>
         <tr>
            <td>Total</td><td></td><td>7</td><td></td><td>-0.16667</td><td></td><td>49</td><td></td><td>-30.6667</td><td></td><td>1.8333</td><td></td><td>-36.1666</td><td></td><td>9.16667</td><td></td><td>0</td>
         </tr>
      </table>
   </body>
</html>